version: '3.9'

services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${NAME}
    ports:
      - '5432:5432'
    networks:
      - journeys-network

  app:
    image: javajourney
    ports:
      - "8080:8080"
    environment:
      DB_USER: ${USER}
      DB_PASSWORD: ${PASSWORD}
      DB_NAME: ${NAME}
      DB_HOST: db:5432
    depends_on:
      - db
    networks:
      - journeys-network

networks:
  journeys-network:
    driver: bridge